server:
  port: 8080
  servlet:
    context-path: /code_generation_service
    #会话超时：秒
    session:
      timeout: 3000

spring:
  main:
    #当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
  #指定日期格式，比如yyyy-MM-dd HH:mm:ss
  date-format: yyyy-MM-dd HH:mm:ss
  #指定日期格式化时区
  time-zone: GMT+8
  mvc:
    view:
      suffix: .jsp
      prefix: /

  #服务模块
  devtools:
    restart:
      #热部署开关
      enabled: true


logging:
  config: classpath:platform_log4j2.xml
  level:
    com.syhc: debug
